<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DSCParser.Shared</AssemblyName>
    <RootNamespace>DSCParser.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="All" />
  </ItemGroup>

</Project>
