<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DSCParser.PSDSC</AssemblyName>
    <RootNamespace>DSCParser.PSDSC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DSCParser.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" PrivateAssets="All" />
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSCParser.Shared\DSCParser.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="DSCParser.PSDSC.psd1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
