<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DSCParser.CSharp</AssemblyName>
    <RootNamespace>DSCParser.CSharp</RootNamespace>
    <IsPackable>true</IsPackable>
    <Description>Parses DSC configurations into objects and back, without compiling them.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSCParser.PSDSC\DSCParser.PSDSC.csproj" />
    <ProjectReference Include="..\DSCParser.Shared\DSCParser.Shared.csproj" />
  </ItemGroup>

</Project>
