<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>DSCParser.CSharp</AssemblyName>
    <RootNamespace>DSCParser.CSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" />
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSCParser.Shared\DSCParser.Shared.csproj" />
  </ItemGroup>

</Project>
